name: Deploy App

on:
  push:
    branches: [ "master", "ci-playground" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to pass
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Run tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 5
      - uses: actions/checkout@v3
      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_PRIVKEY }}" > ~/.ssh/id
          chmod 600 ~/.ssh/id
          ssh-keyscan -H "${{ secrets.DEPLOY_SSH_HOST }}" > ~/.ssh/known_hosts
      - name: Run update script on server
        run: ssh -i ~/.ssh/id root@${{ secrets.DEPLOY_SSH_HOST }} -t 'update-devops-demo-app'
